Repository keenethics/mayak, pull requests merged in 2024-03, with the labels that each got.

#26 [MID-6] list specialists and organizations
  Dockerfile
  prisma/seed.mjs
  src/app/admin/AdminApp.js
  src/app/admin/_components/Organization/List.js
  src/app/admin/_components/Organization/Show.js
  src/app/admin/_components/Organization/index.js
  src/app/admin/_components/Specialist/List.js
  src/app/admin/_components/Specialist/Show.js
  src/app/admin/_components/Specialist/index.js
  src/app/admin/filters.js
  src/app/api/admin/[...slug]/route.js
  src/lib/consts.js
Labels: testing

#54 [MID-40] edit event
  src/app/_components/PillButton/component.js
  src/app/admin/AdminApp.js
  src/app/admin/_components/Event/Create.js
  src/app/admin/_components/Event/Edit.js
  src/app/admin/_components/Event/EventForm.js
  src/app/admin/_components/Event/List.js
  src/app/admin/_components/Event/TagSelect.js
  src/app/admin/_components/Event/index.js
  src/app/admin/_lib/translations.js
  src/app/admin/_lib/validationSchemas/eventSchema.js
  src/app/admin/_utils/transformEventCreateData.js
  src/app/admin/_utils/transformEventEditData.js
  src/app/admin/filters.js
  src/app/api/admin/[...slug]/route.js
  src/lib/consts.js
Labels: testing

#41 [MID-12] Delete specialist/organization
  src/app/(admin)/admin/AdminApp.js
  src/app/(admin)/admin/_components/Organization/List.js
  src/app/(admin)/admin/_components/Organization/Show.js
  src/app/(admin)/admin/_components/Specialist/List.js
  src/app/(admin)/admin/_components/Specialist/Show.js
Labels: testing

#70 [MID-118] email/phone validation bug fix
  src/app/(admin)/admin/_components/MatchingEntityList.js
  src/app/(admin)/admin/_components/MatchingEntityListItem.js
  src/app/(admin)/admin/_hooks/useFindEntityMatchingPhoneOrEmail.js
  src/app/_components/CardSpecialist/CardModalWrapper.js
  src/app/_components/Feedback.js
  src/app/_components/Modal/Modal.js
Labels: bug

#72 [MID-105] Update social links
  prisma/seedDev.mjs
  src/app/(admin)/admin/_components/ServiceProvider/AddressesForm.js
  src/app/(admin)/admin/_components/ServiceProvider/DescriptionEdit.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/Create.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/DetailsEditOrg.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/Edit.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/GeneralInfoEditOrg.js
  src/app/(admin)/admin/_components/ServiceProvider/ServicesForm.js
  src/app/(admin)/admin/_components/ServiceProvider/SocialLinks.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/Create.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/DetailsEditSpec.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/Edit.js
  src/app/(admin)/admin/_components/TextInputList.js
  src/app/(admin)/admin/_lib/consts.js
  src/app/(admin)/admin/_lib/validationSchemas/specialistCommonSchemas.js
  src/app/(admin)/admin/_utils/transformOrganizationData.js
  src/app/(admin)/admin/_utils/transformOrganizationEditData.js
  src/app/(admin)/admin/_utils/transformSpecialistEditData.js
  src/app/(admin)/admin/_utils/transformSpecialistFormData.js
  src/app/_components/CardSpecialist/DetailsList.js
  src/app/_components/CardSpecialist/SocialsList.js
  src/app/_components/CardSpecialist/Specialist/Card.js
Labels: enhancement

#88 [MID-127] fixed contragents results count
  package-lock.json
  package.json
  src/app/_components/Specialists/SpecialistList.js
Labels: bug

#89 [MID-135] Slider bug fix
  src/app/_components/MainPageSections/DistrictList.js
  src/app/_components/MainPageSections/DistrictSearchSection.js
  src/app/_components/Slider.js
Labels: bug

#87 [MID-92] add work time
  prisma/migrations/20240320172637_add_work_time/migration.sql
  prisma/schema.prisma
  prisma/seedDev.mjs
  src/app/(admin)/admin/_components/ServiceProvider/Organization/Create.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/Edit.js
  src/app/(admin)/admin/_components/ServiceProvider/Organization/Show.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/Create.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/Edit.js
  src/app/(admin)/admin/_components/ServiceProvider/Specialist/Show.js
  src/app/(admin)/admin/_components/ServiceProvider/WorkTimeForm.js
  src/app/(admin)/admin/_components/ServiceProvider/WorkTimeShow.js
  src/app/(admin)/admin/_lib/consts.js
  src/app/(admin)/admin/_lib/validationSchemas/specialistCommonSchemas.js
  src/app/(admin)/admin/_utils/common.js
  src/app/(admin)/admin/_utils/transformOrganizationData.js
  src/app/(app)/specialist/consts.js
  src/app/_components/CardSpecialist/Organization/Card.js
  src/app/_components/CardSpecialist/Specialist/Card.js
  src/app/_components/CardSpecialist/WorkTime.js
  src/app/_components/CardSpecialist/config.js
  src/app/api/admin/[...slug]/route.js
  src/app/api/admin/common.js
  src/app/api/search/route.js
  src/utils/common.js
Labels: testing
