Repository keenethics/mayak, pull requests merged in 2024-02, with the labels that each got.

#10 [MID-20] add theme & basic styles based on figma ui kit
  .eslintrc.js
  .gitignore
  .prettierrc.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.js
  src/app/_components/Footer/Footer.js
  src/app/_components/Header/Header.js
  src/app/admin/adminApp.js
  src/app/api/admin/[...slug]/route.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/styles.module.scss
  src/app/styles/font.js
  src/app/styles/tailwind/index.js
  src/app/styles/tailwind/ui/colors.js
  src/app/styles/tailwind/ui/index.js
  src/app/styles/tailwind/ui/screens.js
  src/app/styles/tailwind/ui/typography.js
  src/lib/auth.js
  tailwind.config.mjs
Labels: enhancement

#31 [MID-56] how to set up a db on vercel
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLinters/eslint.xml
  .idea/markdown.xml
  .idea/prettier.xml
  .idea/tailwindcss.xml
  .idea/vcs.xml
  .idea/workspace.xml
  docs/HOWTO.md
  vercel.json
Labels: documentation

#34 [MID-38] add new event
  jsconfig.json
  package-lock.json
  package.json
  prisma/migrations/20240219223854_added_events_table/migration.sql
  prisma/schema.prisma
  prisma/seed.mjs
  src/app/admin/AdminApp.js
  src/app/admin/_components/Event/Create.js
  src/app/admin/_components/Event/TagSelect.js
  src/app/admin/_components/Event/index.js
  src/app/admin/_lib/consts.js
  src/app/admin/_lib/validationSchemas/createEventSchema.js
  src/app/admin/_utils/transformEventData.js
  src/lib/validationSchemas/sendFeedbackSchema.js
  src/lib/validationSchemas/utils.js
Labels: testing

#40 [MID-8] add new organization
  prisma/migrations/20240222155749_added_organization_table/migration.sql
  prisma/schema.prisma
  prisma/seed.mjs
  src/app/admin/AdminApp.js
  src/app/admin/_components/Organization/Create.js
  src/app/admin/_components/Organization/CreateAdresses.js
  src/app/admin/_components/Organization/SelectFormat.js
  src/app/admin/_components/Organization/SelectOrgType.js
  src/app/admin/_components/Organization/SelectTherapies.js
  src/app/admin/_components/Organization/index.js
  src/app/admin/_lib/consts.js
  src/app/admin/_lib/validationSchemas/createOrganizationSchema.js
  src/app/admin/_utils/transformOrganizationData.js
  src/app/api/admin/[...slug]/route.js
Labels: testing
